WebApp/urls.py
from django.urls import include, path
from . import views
# (. significa que importa views da mesma directoria)

urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.loginview, name="login"),
    path('cart/', views.cart, name='cart'),
    # path('register', views.register, name="register"),
    # path('order', views.order, name='order'),
    path('<int:product_id>/product', views.product_detail, name='product'),
    path('<int:product_id>/edit_product', views.edit_product, name='edit_product'),
    path('cart/<int:product_id>/add/', views.add2cart, name='add2cart'),
    path('cart/<int:product_id>/remove/', views.removefromcart, name='removefromcart'),
    path('logout', views.logoutview, name='logout'),
    path('checkout', views.checkout, name='checkout'),
    path('end_order/', views.end_order, name='end_order'),
    path('create_product/', views.create_product, name='create_product'),
    path('<int:product_id>/delete_product/', views.delete_product, name='delete_product'),
    path('profile', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('registration/', views.registration, name='registration'),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('getdressed/', include('WebApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebApp/models.py
from django.contrib.auth.models import User
# from django.core.checks import Tags
from django.db import models
import djangoProject.settings


# Create your models here.
# modelos de dados : Produto, Carrinho, Encomenda, Utilizador
class Size(models.Model):
    nome = models.CharField(max_length=10)

    def __str__(self):
        return self.nome


class Category(models.Model):
    name = models.CharField(max_length=50) #sapatos, camisolas, casacos, etc.
    sizes = models.ManyToManyField(Size)


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300, default="Sem descrição")
    stock = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='images/', default=None)

    def __str__(self):
        return self.name


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    profile_image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, through="CartProduct")

    # last_change = models.DateTimeField()
    def __str__(self):
        return self.client.name + str(self.product.all())


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "carrinho de:" + self.cart.client.name + "adicionado "\
            + self.product.name + ". quantidade: " + str(self.amount)


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.RESTRICT)
    products = models.
    (Product, through="ProductOrder")
    payment_method = models.CharField(max_length=30)
    charged = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.client.name + " : " + str(self.products.all()) + \
            " : " + self.payment_method + " : " + str(self.charged)


class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    def __str__(self):
        return self.product.name + " adicionado à encomenda de: " + \
            self.order.client.name + ". quantidade: " + str(self.amount)

WebApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'stock', 'price', 'category', 'image']


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'profile_image']


class ProductSearchForm(forms.Form):
    search_query = forms.CharField(label='Pesquisar produto', max_length=100)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

WebApp/views.py
# Create your views here.
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Product, Cart, Order, Client
from .forms import *


@login_required(login_url='login')
def home(request):
    form = ProductSearchForm()
    products = Product.objects.all()

    if request.method == 'GET' and 'search_query' in request.GET:
        search_query = request.GET['search_query']
        if search_query:
            products = products.filter(name__icontains=search_query)

    context = {
        'form': form,
        'products': products,
    }
    return render(request, 'home.html', context)


def loginview(request):
    form = AuthenticationForm(request, data=request.POST or None)
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('home')
    return render(request, 'login.html', {'form': form})


def logoutview(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def cart(request):
    # in_cart = Cart.user.cart_set
    return render(request, 'cart.html')


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {"product": product}
    return render(request, 'product.html', context)


def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('edit_product', product_id=product_id)
    else:
        form = ProductForm(instance=product)
    return render(request, 'editProduct.html', {"form": form, "product": product})


@login_required(login_url='login')
def cart(request):
    # Obtém o cliente associado ao usuário atual
    client = request.user.client
    # Obtém o carrinho do cliente
    if not Cart.objects.filter(client_id=client.id):
        Cart.objects.create(client=client)
    cart = client.cart
    # Obtém todos os produtos do carrinho
    products = cart.product.all()
    # Renderiza o template de exibição do carrinho com os produtos
    return render(request, 'cart.html', {'products': products})


def removefromcart(request, product_id):
    cart = request.user.client.cart
    product = get_object_or_404(Product, id=product_id)
    existing_cart_product = CartProduct.objects.filter(cart=cart, product=product)
    if existing_cart_product:
        existing_cart_product = existing_cart_product[0]
    if existing_cart_product.amount > 1:
        existing_cart_product.amount -= 1
        existing_cart_product.save()
    else:
        existing_cart_product.delete()
        cart.product.remove(product)
        cart.save()

    return redirect('cart')


@login_required(login_url='login')
def add2cart(request, product_id):
    cart = request.user.client.cart
    product = get_object_or_404(Product, id=product_id)
    existing_cart_product = CartProduct.objects.filter(cart=cart, product=product)
    if existing_cart_product:
        existing_cart_product = existing_cart_product[0]
        existing_cart_product.amount += 1
        existing_cart_product.save()
    else:
        new_cart_product = CartProduct(cart=cart, product=product, amount=1)
        new_cart_product.save()
    cart.product.add(product)
    cart.save()
    return redirect('home')


def checkout(request):
    cart = request.user.client.cart
    cart_products = CartProduct.objects.filter(cart=cart)
    products = cart.product.all()
    total = sum(cp.product.price * cp.amount for cp in cart_products)
    context = {
        'products': products,
        'total': total
    }
    return render(request, 'checkout.html', context)


def end_order(request):
    cart = request.user.client.cart
    CartProduct.objects.filter(cart=cart).delete()
    return redirect('home')


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ProductForm()
    return render(request, 'create_product.html', {'form': form})


def delete_product(request, product_id):
    Product.objects.filter(id=product_id).delete()
    return redirect('home')


def user_profile(request):
    return render(request, 'profile.html')


def edit_profile(request):
    client = Client.objects.get(user=request.user)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            return redirect('user_profile')
    else:
        form = ClientForm(instance=client)

    return render(request, 'editProfile.html', {'form': form})


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log in the user
            client = Client.objects.create(user=user, name=user.username)
            Cart.objects.create(client=client)
            login(request, user)
            return redirect('home')  # replace 'home' with the name of your homepage url
    else:
        form = RegistrationForm()
    return render(request, 'registration.html', {'form': form})

WebApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style/css/style.css' %}">
</head>
<body>
<header>
        {% if user.client %}
        <a href={% url "cart" %}><button id="cart_btn">
            Ver Carrinho
        </button></a>
        {% endif %}

        <a href={% url "home" %}>
        <img src="{% static 'style/img/GetdressedLOGO.png' %}" alt="getdressed.logo"
             id="home_logo">
        </a>


        <div class="user-buttons">
            <a href={% url 'user_profile' %}><h1>{{ user.username }}</h1></a>
        </div>


</header>

</body>
</html>

WebApp/templates/cart.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
    <meta charset="UTF-8">
    <title>My Cart</title>
</head>
<body>
{% block content %}
{% csrf_token %}
<h1>O Seu Carrinho</h1>
{% if products %}
<ul>
    {% for product in products %}
    <li>
        <h3>{{ product.name }} - {{ product.price }} €- Quantidade: {{product.cartproduct_set.first.amount}}</h3>

        <form method="post" action="{% url 'removefromcart' product_id=product.id %}">
            {% csrf_token %}
            {% if product.image %}
            <img class="product-image" src="{{ product.image.url }}" alt="{{ product.name }}">
            {% endif %}
            <input type="hidden" name="product_id" value="{{ product.id }}">
            <br>
            <button type="submit" style="background-color: red">Remover</button>
        </form>

        <br>

        <form method="post" action="{% url 'checkout' %}">
            {% csrf_token %}
            <button type="submit" style="background-color: #3e8e41">Proseguir para Pagamento</button>
        </form>
    </li>
    <br>
    {% endfor %}
</ul>
{% else %}
<p>O seu carrinho está vazio.</p>
{% endif %}

{% endblock %}



</body>
</html>

WebApp/templates/checkout.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Finalizar Compra</title>
</head>
<body>
{% block content %}
<h1>Finalizar Compra</h1>
<p>O valor total da sua compra é de {{ total }} €</p>
<form method="post">
    {% csrf_token %}
    <label for="payment_type">Selecione o tipo de pagamento:</label>
    <select name="payment_type" id="payment_type">
        <option value="credit_card">Cartão de Crédito</option>
        <option value="debit_card">Cartão de Débito</option>
        <option value="bank_transfer">Transferência Bancária</option>
        <option value="cash">Dinheiro</option>
    </select>
    <br><br>
    <h2>Produtos no Carrinho:</h2>
    <ul>
        {% for product in products %}
        <li>{{ product.name }} -  {{ product.price }} € - Quantidade: {{ product.cartproduct_set.first.amount }}</li>
        {% endfor %}
    </ul>
    <br>

</form>
<form method="post" action="{% url 'end_order' %}">
    {% csrf_token %}
    <button type="submit">Finalizar compra</button>
</form>
{% endblock %}
</body>
</html>

WebApp/templates/create_product.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
  <meta charset="UTF-8">
  <title>Create Product</title>
</head>
<body>
{% block content %}
{% csrf_token %}
<h1>Criar Novo Produto</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Product</button>
</form>
{% endblock %}
</body>
</html>

WebApp/templates/editProduct.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Editar Produto</title>
</head>
<body>
{% csrf_token %}
<form method="post" enctype="multipart/form-data" action="{% url 'edit_product' product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="background-color: #3e8e41">Salvar</button>
</form>
<br>
<form method="post" enctype="multipart/form-data" action="{% url 'delete_product' product.id %}">
    {% csrf_token %}
    <button type="submit" style="background-color: red">delete</button>
</form>
<br>
<a href={% url 'product' product.id %}>Voltar</a>


</body>
</html>

WebApp/templates/editProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'base.html' %}
    <meta charset="UTF-8">
    <title>Editar Perfil</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Salvar">
</form>

</body>
</html>

WebApp/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    {% include 'base.html' %}
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style/css/style.css' %}">
</head>
<body>
<main>
    {% block content %}

        <div class="search-container">
            <form method="GET" action="{% url 'home' %}">
                    {{ form.search_query }}
                    <button type="submit" class="search-button">Pesquisar</button>
            </form>
        <br>
            {% if user.is_authenticated and user.is_staff %}
                <a href="{% url 'create_product' %}"><button>Criar Produto</button> </a>
            {% endif %}
        </div>


        <section class="product-section">
        {% if products %}
            {% for product in products %}
                <div class="product-item">
                {% if product.image %}
                    <a href={% url "product" product.id %}>
                    <img class="product-image" src="{{ product.image.url }}" alt="">
                    </a>
                {% endif %}
                    <br>
                    {{ product.name }} : {{ product.price }} €
                </div>
            {% endfor %}
        {% endif %}

        </section>
    {% endblock %}
</main>




</body>
</html>

WebApp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style/css/style.css' %}">
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login" id="login_submit"/>
</form>
{# <a href="{% url 'getdressed:register' %}">Não tem conta? Registre-se aqui</a>#}
<a href="{% url 'registration' %}">Registar</a>

</body>
</html>

WebApp/templates/product.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Produto</title>
</head>

<body>
<h2>{{ product.name }}</h2>
{% csrf_token %}
{% if product.image %}
    <img class="product-image" src="{{ product.image.url }}" alt="{{ product.name }}">
{% endif %}

<h3>{{ product.price }} €</h3>
<h3>{{ product.description }}</h3>

{% if user.client %}
<form method="post" action="{% url 'add2cart' product_id=product.id %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <button type="submit">Adicionar ao Carrinho</button>
</form>
{% endif %}

<br>
{% if user.is_authenticated and user.is_staff %}
    <a href={% url "edit_product" product.id %}><button>Editar</button></a>
{% endif %}

</body>
</html>

WebApp/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'base.html' %}
    <meta charset="UTF-8">
    <title>Perfil do Utilizador</title>
</head>
<body>
{% block content %}

    <ul>
        {% if user.client %}
            <li><h1>{{ user.client.name }}</h1></li>
            {% if user.client.profile_image %}
                <br>
                <li>
                    <img class="product-image" src="{{ user.client.profile_image.url }}" alt="default">
                </li>
                {% else %}
                <li>
                    <img src="{% static 'media/images/default_client.png' %}"
                         alt="default" style="height:200px; width:200px">
                </li>
            {% endif %}
                <li><a href={% url "edit_profile" %}><button style="background-color: dodgerblue">Editar Perfil</button></a></li>
        {% endif %}
            <li>
                <a href={% url "logout" %}>
                    <button class="logout-button">
                    Encerrar Sessão
                    </button>
                </a>
            </li>
    </ul>





{% endblock %}

</body>
</html>

WebApp/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style/css/style.css' %}">
</head>
<body>
<h1>Registo</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submeter</button>
</form>
<br>
<a href={% url "login"%}><button>Já tem conta?! Login aqui</button></a>
</body>
</html>